import { ConvexClientProvider } from "../components/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Model from "@/components/Model";
import { Toaster } from "@/components/ui/sonner";
import Jotai from "@/components/JotaiProvider";
import { Providersnqus } from "./Provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Slacky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Providersnqus>

       <ConvexClientProvider> 
        <Jotai > {/** Jotai apna synhronously share krega sab ko  */}
       <Model/>   
        <Toaster/>
        {children} 
        </Jotai>
        </ConvexClientProvider>
      </Providersnqus>
      </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
